audit.kafka.topic=audit-events

spring.application.name=audit-event-consumer

spring.kafka.consumer.group-id=oidc-audit-consumer
spring.kafka.bootstrap-servers=localhost:9092

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.threads.virtual.enabled=true