audit.kafka.topic=audit-events

spring.application.name=audit-event-producer

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server.port=8081

#This is actually the default, just adding here to recall setting
spring.kafka.producer.properties.enable.idempotence=true